# Generated by Django 5.0.1 on 2024-02-06 19:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CRModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.DateField()),
                ('installed_datetime', models.DateTimeField()),
                ('replaced_datetime', models.DateTimeField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['-installed_datetime'],
            },
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('crmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.crmodel')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('discount_rate', models.DecimalField(decimal_places=10, max_digits=10, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)])),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            bases=('infrastructure.crmodel',),
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('crmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.crmodel')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('calculate_change', models.BooleanField(default=False, verbose_name='For this payment method, calculate change returned to customer')),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('infrastructure.crmodel',),
        ),
        migrations.CreateModel(
            name='TaxCategory',
            fields=[
                ('crmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.crmodel')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('tax_rate', models.DecimalField(decimal_places=10, max_digits=10, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)])),
                ('order', models.IntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('infrastructure.crmodel',),
        ),
        migrations.CreateModel(
            name='FKey',
            fields=[
                ('crmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.crmodel')),
                ('key', models.CharField(choices=[('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5'), ('F6', 'F6'), ('F7', 'F7'), ('F8', 'F8'), ('F9', 'F9'), ('F10', 'F10'), ('F11', 'F11'), ('F12', 'F12'), ('ESC', 'ESC'), ('/', '/'), ('*', '*'), ('-', '-'), ('+', '+'), ('.', '.'), ('PageDown', 'PageDown'), ('PageUp', 'PageUp')], max_length=8, unique=True)),
                ('key_type', models.CharField(blank=True, choices=[('PaymentType', 'PaymentType'), ('TaxCategory', 'TaxCategory'), ('Discount', 'Discount')], editable=False, max_length=11, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('discount_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.discounttype')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.paymenttype')),
                ('tax_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.taxcategory')),
            ],
            options={
                'ordering': ['display_order'],
            },
            bases=('infrastructure.crmodel',),
        ),
    ]
