# Generated by Django 5.0.1 on 2024-02-12 19:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyUnits',
            fields=[
                ('crmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.crmodel')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('unit_symbol', models.CharField(max_length=2, unique=True)),
                ('value_ratio', models.DecimalField(decimal_places=10, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('step_size', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('infrastructure.crmodel',),
        ),
    ]
