# Generated by Django 5.0.1 on 2024-02-12 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_rename_currencyunits_currencyunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyunit',
            name='value_ratio',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
