# Generated by Django 5.0.1 on 2024-06-27 16:48

import django.db.models.deletion
import infrastructure.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_alter_currencyunit_value_ratio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='crmodel',
            name='company',
            field=models.ForeignKey(default=infrastructure.models.Company.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.company'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('crmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.crmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('infrastructure.crmodel',),
        ),
        migrations.DeleteModel(
            name='CurrencyUnit',
        ),
    ]
