# Generated by Django 5.0.1 on 2024-06-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_company_crmodel_company_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency_sym',
            field=models.CharField(default='$', max_length=4),
        ),
        migrations.AddField(
            model_name='company',
            name='price_divisor',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='company',
            name='price_format',
            field=models.FloatField(default=2),
        ),
        migrations.AddField(
            model_name='company',
            name='price_stepsize',
            field=models.CharField(default='0.01', max_length=20),
        ),
    ]
