# Generated by Django 5.0.1 on 2024-12-01 21:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPurchase',
            fields=[
                ('crmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.crmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=('infrastructure.crmodel',),
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('crmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.crmodel')),
                ('price', models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_price', models.DecimalField(blank=True, decimal_places=10, editable=False, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('debit', models.BooleanField(default=True, editable=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('customer_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.customerpurchase')),
                ('discount_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.discounttype')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.paymenttype')),
                ('tax_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.taxcategory')),
            ],
            options={
                'ordering': ['customer_purchase', '-created_at'],
            },
            bases=('infrastructure.crmodel',),
        ),
    ]
