# Generated by Django 5.0.1 on 2024-02-12 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_alter_currencyunit_value_ratio'),
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='currency_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.currencyunit'),
            preserve_default=False,
        ),
    ]
