# Generated by Django 5.0.1 on 2024-02-12 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_alter_currencyunit_value_ratio'),
        ('operations', '0002_lineitem_currency_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='currency_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.currencyunit'),
        ),
    ]
