# Generated by Django 5.0.1 on 2024-02-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_lineitem_currency_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='currency_unit',
        ),
    ]
